### ISSUE TITLE
Missing units on NBN upgrade map

### ISSUE THREAD

**Issue by Southerngal** [LukePrior/nbn-upgrade-map#207] opened 2023-07-16 08:46 UTC
I was looking on the map and notice it is missing my Unit 3 + Unit 1 and 4.    On the map it shows Unit 2/136 for my street address.  

I'm connected on FTTN and in an area waiting for FTTP upgrades. (By end of December 2023.)

I'm wondering if your map will be updated to include the missing units as well across the states in Australia for local names of places?

Thank you for the amazing work on the NBN FTTN upgrades to FTTP.  It is quite handy.

**Comment by lyricnz** [comment] 2023-07-16 09:22
I will need more information to look into this. We use the gnaf database of addresses - is your unit very new?  Can you find all four addresses on the nbnco website checker?  I will need to know the address to look into your specific case…

**Comment by Southerngal** [comment] 2023-07-16 09:35
Hi there,

Yes, all the four units addresses is on nbnco website checker.

No - the units built since 2003.

If I could message you privately for the address..  screenshot of the map.

**Comment by lyricnz** [comment] 2023-07-16 09:40
You can email me @gmail

**Comment by Southerngal** [comment] 2023-07-16 09:51
Hi there,

Here's the screenshot of the map.

Hope this helps.

Cheers

Southerngal

**Comment by lyricnz** [comment] 2023-07-16 22:42
Sorry I don't see any screenshot?

**Comment by Southerngal** [comment] 2023-07-16 23:09
Have just sent the screenshot map to your correct gmail.

**Comment by lyricnz** [comment] 2023-07-17 00:40
Got your email.  All four units (plus the base address) are in the geojson file, and on the map, but the problem is that they all have exactly the same lat/long coordinates, so clicking on the spot brings up one of them (the last/top one as it happens). I'm going to have to get @LukePrior to look at that, as I'm not a javascript person.

**Comment by LukePrior** [comment] 2023-07-17 03:11
Interesting will look into how best to show this on the map.

**Comment by LukePrior** [comment] 2023-07-17 11:07
I've given it a shot here, not sure if I'm really happy with it yet: https://github.com/LukePrior/nbn-upgrade-map/commit/82f07a3f4a4069f76fcc39b43deea615f5a1e840

**Comment by Southerngal** [comment] 2023-07-17 11:22
Good on ya for trying resolve this issues.   

Hopefully you will find something you will be happy with for an exactly same lat/long coordinates for units etc on the map.  I'm sure you will figure it out eventually.  

Thank you to you both Lyricnz and LukePrior.

**Comment by LukePrior** [comment] 2023-07-30 08:02
I will close this for now but consider further improvements in future

**Closed by LukePrior** 2023-07-30 08:02 UTC
Labels: enhancement
